In [2]:
import tensorflow as tf
import numpy as np

In [16]:
print(tf.__version__)
session = tf.InteractiveSession()

0.12.1


In [37]:
# Using the tf.split method
# We can imagine that:
# 2 is the number of images
# 2 is the width of the image pixel-wise
# 2 is the height of the image pixel-wise
# 3 is the RBG of each pixel
X = tf.constant(np.random.randn(2, 2, 2, 3))
print(X.eval())

[[[[ 0.07135518  1.4067804  -1.46384131]
   [-0.82587093 -0.23383764 -0.17479868]]

  [[ 0.97639385  1.09180426 -1.1754418 ]
   [-3.07314672 -1.03097413  1.19073967]]]


 [[[-1.29151613 -2.05434197  0.28282473]
   [-0.44421948 -1.46595107 -0.92635151]]

  [[ 0.79374907  0.21626931 -0.08926941]
   [ 0.92807732 -0.03165952 -0.04967937]]]]


In [39]:
# tf.split(arg1, arg2, arg3)
# arg1 is the axis of the split
# arg2 is the number of equal partitions after the split
# arg3 is the input data

# Split by image
split0, split1 = tf.split(0, 2, X)
print(X.eval())
print()
print(split0.eval())

[[[[ 0.07135518  1.4067804  -1.46384131]
   [-0.82587093 -0.23383764 -0.17479868]]

  [[ 0.97639385  1.09180426 -1.1754418 ]
   [-3.07314672 -1.03097413  1.19073967]]]


 [[[-1.29151613 -2.05434197  0.28282473]
   [-0.44421948 -1.46595107 -0.92635151]]

  [[ 0.79374907  0.21626931 -0.08926941]
   [ 0.92807732 -0.03165952 -0.04967937]]]]

[[[[ 0.07135518  1.4067804  -1.46384131]
   [-0.82587093 -0.23383764 -0.17479868]]

  [[ 0.97639385  1.09180426 -1.1754418 ]
   [-3.07314672 -1.03097413  1.19073967]]]]


In [40]:
split0, split1 = tf.split(1, 2, X)
print(X.eval())
print()
print(split0.eval())

[[[[ 0.07135518  1.4067804  -1.46384131]
   [-0.82587093 -0.23383764 -0.17479868]]

  [[ 0.97639385  1.09180426 -1.1754418 ]
   [-3.07314672 -1.03097413  1.19073967]]]


 [[[-1.29151613 -2.05434197  0.28282473]
   [-0.44421948 -1.46595107 -0.92635151]]

  [[ 0.79374907  0.21626931 -0.08926941]
   [ 0.92807732 -0.03165952 -0.04967937]]]]

[[[[ 0.07135518  1.4067804  -1.46384131]
   [-0.82587093 -0.23383764 -0.17479868]]]


 [[[-1.29151613 -2.05434197  0.28282473]
   [-0.44421948 -1.46595107 -0.92635151]]]]


In [41]:
split0, split1 = tf.split(2, 2, X)
print(X.eval())
print()
print(split0.eval())

[[[[ 0.07135518  1.4067804  -1.46384131]
   [-0.82587093 -0.23383764 -0.17479868]]

  [[ 0.97639385  1.09180426 -1.1754418 ]
   [-3.07314672 -1.03097413  1.19073967]]]


 [[[-1.29151613 -2.05434197  0.28282473]
   [-0.44421948 -1.46595107 -0.92635151]]

  [[ 0.79374907  0.21626931 -0.08926941]
   [ 0.92807732 -0.03165952 -0.04967937]]]]

[[[[ 0.07135518  1.4067804  -1.46384131]]

  [[ 0.97639385  1.09180426 -1.1754418 ]]]


 [[[-1.29151613 -2.05434197  0.28282473]]

  [[ 0.79374907  0.21626931 -0.08926941]]]]


In [57]:
split0, split1, split2 = tf.split(3, 3, X)
print(X.eval())
print()
print(split0.eval())

[[[[ 0.07135518  1.4067804  -1.46384131]
   [-0.82587093 -0.23383764 -0.17479868]]

  [[ 0.97639385  1.09180426 -1.1754418 ]
   [-3.07314672 -1.03097413  1.19073967]]]


 [[[-1.29151613 -2.05434197  0.28282473]
   [-0.44421948 -1.46595107 -0.92635151]]

  [[ 0.79374907  0.21626931 -0.08926941]
   [ 0.92807732 -0.03165952 -0.04967937]]]]

[[[[ 0.07135518]
   [-0.82587093]]

  [[ 0.97639385]
   [-3.07314672]]]


 [[[-1.29151613]
   [-0.44421948]]

  [[ 0.79374907]
   [ 0.92807732]]]]


In [54]:
# Generic zip function in python
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[11,22,33],[44,55,66]])
z = list(zip(x,y))
zipped_list = z[:]
print(zipped_list)

[(array([1, 2, 3]), array([11, 22, 33])), (array([4, 5, 6]), array([44, 55, 66]))]


In [58]:
# Mimicking the tf.nn.local_response_normalization
x

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
X = tf.constant(np.random.randn(2, 2, 2, 3))
print(X.eval())

[[[[ 0.15598753 -0.14767144 -0.09557633]
   [ 0.07094406  1.4968308  -1.03763217]]

  [[-2.08347437 -0.45481982  0.11317302]
   [-0.87570811  0.12161626 -0.44293157]]]


 [[[-1.55761709 -1.10371149 -0.28278131]
   [-0.35618879 -1.01916274 -1.07957081]]

  [[-0.05809574 -0.84932452 -1.70572208]
   [ 0.13609637  0.13374197 -1.52302799]]]]


In [64]:
X[1,1,1,0:3].eval()

array([ 0.13609637,  0.13374197, -1.52302799])

In [26]:
# Initializing tf.variables
v = tf.Variable(0.1)
tf.global_variables_initializer().run()
print(v.eval())

0.1
