In [7]:
import tensorflow as tf
import numpy as np
session = tf.InteractiveSession()

In [5]:
x = np.array(range(12)).reshape(2,2,3)
x

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [8]:
arr_t = tf.transpose(x, perm= [0, 2, 1])

print(arr_t.eval())

[[[ 0  3]
  [ 1  4]
  [ 2  5]]

 [[ 6  9]
  [ 7 10]
  [ 8 11]]]


In [9]:
arr_t = tf.transpose(x, perm = [0, 1, 2])
print(arr_t.eval())

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [10]:
arr_t = tf.transpose(x, perm = [2, 1, 0])
print(arr_t.eval())

[[[ 0  6]
  [ 3  9]]

 [[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]]


In [11]:
arr_t = tf.transpose(x, perm = [2, 0, 1])
print(arr_t.eval())

[[[ 0  3]
  [ 6  9]]

 [[ 1  4]
  [ 7 10]]

 [[ 2  5]
  [ 8 11]]]
